title: Code Reproducibility Training 
# this appears in the html browser tab for the site title (seen mostly by search engines, not users)

topnav_title: ''
# this appears on the top navigation bar next to the home button

description: Training material on how to make code FAIR
# Metadata description of the website

remote_theme: ELIXIR-Belgium/elixir-toolkit-theme@1.25.0

#training_link_prefix: https://elixir-europe-training.github.io/

theme_variables:
  theme_color: da366e
  fonts:
    - https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;1,100;1,200;1,300;1,400;1,500;1,600;1,700&display=swap
  github_buttons:
    position: top
    edit_me: true
    open_issue: true
    history: true
  topnav:
    theme: light
    brand_logo: assets/img/code-rep-web-icon.png
    github: true

permalink: pretty

exclude:
  - README.md
  - .gitignore
  - var/
  - vendor
  - Gemfile*
  - LICENSE

defaults:
-
  scope:
    path: ""
    type: "pages"
  values:
    permalink: /:basename
    layout: "page"
    sidebar: main
    topnav: topnav
-
  scope:
    path: "pages/lessons"
    type: "lessons"
  values:
    permalink: /:basename
    layout: "page"
    topnav: topnav
-
  scope:
    path: "pages/team"
    type: "pages"
  values:
    permalink: /:basename
    layout: "page"
    topnav: topnav

-
  scope:
    path: "pages/contribute"
    type: "pages"
  values:
    permalink: /:basename
    layout: "page"
    topnav: topnav

plugins:
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
